/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul7_2;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/**
 *
 * @author ILHAM
 */
public class frame1 extends javax.swing.JFrame {

    /**
     * Creates new form frame1
     */
    public frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Tinggi = new javax.swing.JTextField();
        Lebar = new javax.swing.JTextField();
        Panjang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Sisi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Jari = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Program Pencari Volume Bangun Ruang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 20, 330, 60);

        jPanel1.setLayout(null);

        jLabel7.setText("CM");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(390, 120, 40, 40);

        jLabel6.setText("CM");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(390, 60, 50, 40);

        jLabel5.setText("CM");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(390, 180, 40, 40);
        jPanel1.add(Tinggi);
        Tinggi.setBounds(210, 180, 150, 40);
        jPanel1.add(Lebar);
        Lebar.setBounds(210, 120, 150, 40);
        jPanel1.add(Panjang);
        Panjang.setBounds(210, 60, 150, 40);

        jLabel3.setText("Masukkan Panjang");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(41, 63, 140, 40);

        jLabel4.setText("Masukkan Lebar");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 120, 140, 40);

        jLabel2.setText("Masukkan Tinggi");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 180, 140, 40);

        jButton1.setText("HITUNG");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(210, 250, 120, 30);

        jTabbedPane1.addTab("Balok", jPanel1);

        jPanel2.setLayout(null);

        jLabel8.setText("Masukkan Panjang Sisi");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(41, 63, 140, 40);
        jPanel2.add(Sisi);
        Sisi.setBounds(210, 60, 150, 40);

        jLabel9.setText("CM");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(390, 60, 50, 40);

        jButton2.setText("Volume");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(210, 130, 120, 30);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel3.setLayout(null);

        jLabel10.setText("Masukkan Panjang Jari - jari");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(21, 63, 160, 40);
        jPanel3.add(Jari);
        Jari.setBounds(210, 60, 150, 40);

        jLabel11.setText("CM");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(390, 60, 50, 40);

        jButton3.setText("Volume");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(210, 130, 120, 30);

        jTabbedPane1.addTab("Bola", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 70, 540, 400);

        setBounds(0, 0, 557, 513);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int panjang,lebar,tinggi;
    panjang = Integer.parseInt(Panjang.getText());
    lebar = Integer.parseInt(Lebar.getText());
    tinggi = Integer.parseInt(Tinggi.getText());
    int hasil = panjang*lebar*tinggi;
    try
    {
        JOptionPane.showMessageDialog(null,"Volume Balok Adalah : "+hasil,"Luas",JOptionPane.INFORMATION_MESSAGE);
    }
    catch(Exception e)
    {     
        JOptionPane.showMessageDialog(null,"Error   :"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int sisi;
        sisi = Integer.parseInt(Sisi.getText());
        int hasil = sisi*sisi*sisi;
        
        try
    {
        JOptionPane.showMessageDialog(null,"Luas Permukaan Kubus Adalah : "+hasil,"Luas",JOptionPane.INFORMATION_MESSAGE);
    }
    catch(Exception e)
    {     
        JOptionPane.showMessageDialog(null,"Error   :"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        float jari;
        jari = Integer.parseInt(Jari.getText());
        float hasil = (float) (4/3*3.14*jari*jari*jari);
        
        try
    {
        JOptionPane.showMessageDialog(null,"Luas Permukaan Bola Adalah : "+hasil,"Luas",JOptionPane.INFORMATION_MESSAGE);
    }
    catch(Exception e)
    {     
        JOptionPane.showMessageDialog(null,"Error   :"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jari;
    private javax.swing.JTextField Lebar;
    private javax.swing.JTextField Panjang;
    private javax.swing.JTextField Sisi;
    private javax.swing.JTextField Tinggi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
